version: '3.8'

services:
  web:
    build: ./app/
    ports:
      - "3000:3000" 
    depends_on:
      - db
    environment:
      - DB_HOST=db 
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME} 
      - JWT_SECRET=${JWT_SECRET} 
    networks:
      - backend

  db:
    image: mariadb:10.5
    volumes:
      - ./db:/var/lib/mysql 
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    networks:
      - backend

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    depends_on:
      - db
    networks:
      - backend

networks:
  backend:
    driver: bridge